# https://docs.docker.com/engine/reference/commandline/compose_up
version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: dogokit-remix-database
    hostname: database
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    env_file:
      - .env

volumes:
  mysql_data:
